sudo: required

language: python

# safelist
branches:
  only:
     - master
     - development

services:
  - docker

before_install:
  - docker build -t sentry/py .
  - docker ps
  - docker images

install: "pip install -r requirements.txt"

before_script:
  - chmod +x ./test.sh
script:
  - ./test.sh
