sudo: required

language: python

# safelist
branches:
  only:
     - master
     - development

services:
  - docker

before_install:
  - docker build -t sentry/py .
  - docker ps

install: "pip install -r requirements.txt"

script: pytest
