sudo: required
dist: trusty

language: python

# safelist
branches:
  only:
    - master
    - development

services:
  - docker

before_install:
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - docker build -t jdpleiness:armhf-sentrypi .
  - docker ps
  - docker images

install: "pip install -r requirements.txt"

before_script:
  - chmod +x ./test.sh

script:
  - ./test.sh
