version: '3'
services:
  computervision:
    restart: always
    image: jdpleiness/armhf-sentrypi 
    devices:
      - "/dev/video0:/dev/video0"
      - "/dev/video1:/dev/video1"
    volumes:
      - /home/pi:/pi
