version: '3'
services:
  computervision:
    restart: always
    image: jdpleiness/armhf-sentrypi 
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
