version: '3'
services:
  computervision:
    restart: always
    image: jdpleiness/armhf-sentrypi 
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    devices:
      - "/dev/video0:/dev/video0"
      - "/dev/video1:/dev/video1"
    volumes:
      - /home/pi:/pi
